"""Records for receiving orgs (section 10) and volunteers.

The report builder uses exactly the fields each org chose in Q3, at its chosen
frequency and format. A delivery missing a field the org needs is flagged
incomplete, and the receipt form prompts for it next time.
"""
from __future__ import annotations

import base64
import csv
import io
from datetime import date, datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy.orm import Session

from app import clock, pdf
from app.assumptions import LBS_PER_MEAL
from app.models import Acknowledgment, OrgReport, ReceiverProfile, Trip, TripStop

FIELD_LABELS = {
    "date_time": "Date/time received", "donor_name": "Donor", "donor_address": "Donor address",
    "food_description": "Food description", "food_category": "Category", "quantity_meals": "Meals",
    "weight_lbs": "Weight (lbs, est. 1.2 lbs/meal)", "temperature_at_receipt": "Temp at receipt (F)",
    "condition": "Condition", "received_by_name": "Received by", "allergen_info": "Allergens",
    "donor_acknowledgment": "Donor acknowledgment",
}


def _value(stop: TripStop, field: str, ack: Optional[Acknowledgment]) -> Any:
    r = stop.trip.rescue
    return {
        "date_time": clock.to_local(stop.received_at).strftime("%Y-%m-%d %H:%M") if stop.received_at else None,
        "donor_name": r.restaurant.name,
        "donor_address": r.restaurant.address or None,
        "food_description": r.description or f"{r.quantity:g} {r.unit.replace('_', ' ')} ({r.category.replace('_', '-')})",
        "food_category": r.category,
        "quantity_meals": stop.received_meals,
        "weight_lbs": round(stop.received_meals * LBS_PER_MEAL, 1) if stop.received_meals is not None else None,
        "temperature_at_receipt": stop.temperature_f,
        "condition": stop.condition,
        "received_by_name": stop.received_by_name or None,
        "allergen_info": (", ".join(r.allergens) or "none declared") if r.allergens_declared else None,
        "donor_acknowledgment": (f"{ack.status}" + (f" by {ack.signer_name}" if ack and ack.signer_name else "")) if ack else None,
    }[field]


def delivery_rows(db: Session, org_id: int, start: date, end: date, fields: List[str]) -> List[Dict[str, Any]]:
    lo, hi = clock.local_to_utc(datetime.combine(start, datetime.min.time())), clock.local_to_utc(datetime.combine(end + timedelta(days=1), datetime.min.time()))
    stops = (db.query(TripStop).join(Trip, Trip.id == TripStop.trip_id)
             .filter(TripStop.organization_id == org_id, TripStop.status.in_(("received", "rejected")),
                     TripStop.received_at >= lo, TripStop.received_at < hi).order_by(TripStop.received_at).all())
    rows = []
    for s in stops:
        ack = db.query(Acknowledgment).filter_by(stop_id=s.id).one_or_none()
        row = {f: _value(s, f, ack) for f in fields}
        missing = [f for f in fields if row[f] in (None, "") and f != "donor_acknowledgment"]
        if missing != (s.incomplete_fields or []):
            s.incomplete_fields = missing
        row["_stop_id"] = s.id
        row["_incomplete"] = missing
        rows.append(row)
    return rows


def render_report(org_name: str, fields: List[str], rows: List[Dict[str, Any]], fmt: str, period: Tuple[date, date],
                  reports_to: str) -> Tuple[str, bytes]:
    header = [FIELD_LABELS[f] for f in fields] + ["Incomplete fields"]
    table = [[("" if r[f] is None else r[f]) for f in fields] + ["; ".join(r["_incomplete"])] for r in rows]
    if fmt == "csv":
        buf = io.StringIO()
        w = csv.writer(buf)
        w.writerow(header)
        w.writerows(table)
        return "text/csv", buf.getvalue().encode()
    lines = [f"Organization: {org_name}", f"Period: {period[0]} to {period[1]}",
             f"Prepared for: {reports_to or 'internal records'}", f"Deliveries: {len(rows)}",
             f"Meals received: {sum((r.get('quantity_meals') or 0) for r in rows)}", ""]
    for r in rows:
        lines.append(" | ".join(f"{FIELD_LABELS[f]}: {'' if r[f] is None else r[f]}" for f in fields))
        if r["_incomplete"]:
            lines.append(f"   INCOMPLETE: missing {', '.join(r['_incomplete'])}")
    lines += ["", "Generated by FoodFlow from records entered at pickup and receipt."]
    return "application/pdf", pdf.render(f"Donation records: {org_name}", lines)


def period_for(freq: str, today: date) -> Tuple[date, date]:
    """The most recent completed period before today."""
    if freq == "weekly":
        end = today - timedelta(days=today.weekday() + 1)
        return end - timedelta(days=6), end
    if freq == "monthly":
        end = today.replace(day=1) - timedelta(days=1)
        return end.replace(day=1), end
    if freq == "quarterly":
        q_start_month = 3 * ((today.month - 1) // 3) + 1
        end = today.replace(month=q_start_month, day=1) - timedelta(days=1)
        return end.replace(month=3 * ((end.month - 1) // 3) + 1, day=1), end
    return today, today  # per_delivery: today's deliveries


def build(db: Session, org_id: int, start: date, end: date, fmt: Optional[str] = None) -> OrgReport:
    p = db.get(ReceiverProfile, org_id)
    fields = list(p.required_fields or ["date_time", "donor_name", "quantity_meals"])
    fmt = fmt or p.report_format or "csv"
    rows = delivery_rows(db, org_id, start, end, fields)
    media, content = render_report(p.organization.name, fields, rows, fmt, (start, end), p.reports_to)
    rep = db.query(OrgReport).filter_by(organization_id=org_id, period_start=start, period_end=end, format=fmt).one_or_none()
    rep = rep or OrgReport(organization_id=org_id, period_start=start, period_end=end, format=fmt, fields=fields, content="")
    rep.fields, rep.row_count, rep.generated_at = fields, len(rows), clock.now()
    rep.content = content.decode() if fmt == "csv" else base64.b64encode(content).decode()
    db.add(rep)
    db.flush()
    return rep


def report_bytes(rep: OrgReport) -> Tuple[str, bytes]:
    return ("text/csv", rep.content.encode()) if rep.format == "csv" else ("application/pdf", base64.b64decode(rep.content))


def generate_due_reports(db: Session) -> int:
    """Create each org's latest completed-period report once (per_delivery orgs: today's, refreshed)."""
    today = clock.to_local(clock.now()).date()
    n = 0
    for p in db.query(ReceiverProfile).filter(ReceiverProfile.report_frequency.isnot(None)).all():
        start, end = period_for(p.report_frequency, today)
        exists = db.query(OrgReport).filter_by(organization_id=p.organization_id, period_start=start, period_end=end,
                                               format=p.report_format).one_or_none()
        if exists is None or p.report_frequency == "per_delivery":
            build(db, p.organization_id, start, end)
            n += 1
    return n


def volunteer_hours(db: Session, user_id: int) -> List[Dict[str, Any]]:
    trips = (db.query(Trip).filter(Trip.volunteer_user_id == user_id, Trip.started_at.isnot(None),
                                   Trip.status.in_(("received", "rejected", "delivered"))).order_by(Trip.started_at).all())
    out = []
    for t in trips:
        end = max((s.received_at for s in t.stops if s.received_at), default=None) or t.finished_at
        if end is None:
            continue
        out.append({"trip_id": t.id, "date": clock.to_local(t.started_at).date().isoformat(),
                    "started": clock.to_local(t.started_at).strftime("%H:%M"), "ended": clock.to_local(end).strftime("%H:%M"),
                    "hours": round((end - t.started_at).total_seconds() / 3600, 2),
                    "restaurant": t.rescue.restaurant.name, "meals": t.picked_up_meals,
                    "organizations": "; ".join(s.organization.name for s in t.stops if s.status in ("received", "rejected"))})
    return out
