"""initial schema: every table in app/models.py, plus the append-only audit_events triggers

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 16:16:07.228615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# audit_events is append-only (see app/db.py); copied here so this migration never changes
APPEND_ONLY = {
    "sqlite": [
        "CREATE TRIGGER IF NOT EXISTS audit_no_update BEFORE UPDATE ON audit_events "
        "BEGIN SELECT RAISE(ABORT, 'audit_events is append-only'); END",
        "CREATE TRIGGER IF NOT EXISTS audit_no_delete BEFORE DELETE ON audit_events "
        "BEGIN SELECT RAISE(ABORT, 'audit_events is append-only'); END",
    ],
    "postgresql": [
        "CREATE OR REPLACE FUNCTION audit_append_only() RETURNS trigger AS $$ "
        "BEGIN RAISE EXCEPTION 'audit_events is append-only'; END; $$ LANGUAGE plpgsql",
        "DROP TRIGGER IF EXISTS audit_no_change ON audit_events",
        "CREATE TRIGGER audit_no_change BEFORE UPDATE OR DELETE ON audit_events "
        "FOR EACH ROW EXECUTE FUNCTION audit_append_only()",
    ],
}
DROP_APPEND_ONLY = {
    "sqlite": ["DROP TRIGGER IF EXISTS audit_no_update", "DROP TRIGGER IF EXISTS audit_no_delete"],
    "postgresql": ["DROP TRIGGER IF EXISTS audit_no_change ON audit_events",
                   "DROP FUNCTION IF EXISTS audit_append_only()"],
}


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('caller', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'caller', name='uq_idem_key_caller')
    )
    op.create_table('job_locks',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_key_at', ['key', 'at'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('public_slug', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("kind IN ('restaurant', 'receiver')", name='ck_org_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_slug')
    )
    op.create_table('impact_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('meals', sa.Integer(), nullable=False),
    sa.Column('weight_lbs', sa.Float(), nullable=False),
    sa.Column('delivery_minutes', sa.Float(), nullable=False),
    sa.Column('is_demo_seed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('meals > 0', name='ck_impact_meals'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_events_delivery_id'), ['delivery_id'], unique=False)

    op.create_table('org_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('format', sa.String(length=5), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'period_start', 'period_end', 'format', name='uq_org_report_period')
    )
    with op.batch_alter_table('org_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_reports_organization_id'), ['organization_id'], unique=False)

    op.create_table('receiving_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'day', name='uq_exception_day')
    )
    with op.batch_alter_table('receiving_exceptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receiving_exceptions_organization_id'), ['organization_id'], unique=False)

    op.create_table('restaurant_profiles',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('closing_times', sa.JSON(), nullable=False),
    sa.Column('staffed_until', sa.JSON(), nullable=False),
    sa.Column('surplus_usually', sa.String(length=200), nullable=False),
    sa.Column('totes_on_hand', sa.Integer(), nullable=False),
    sa.Column('totes_out', sa.Integer(), nullable=False),
    sa.Column('default_fmv_per_meal', sa.Float(), nullable=True),
    sa.Column('default_cost_basis_per_meal', sa.Float(), nullable=True),
    sa.Column('basis_election_25pct', sa.Boolean(), nullable=False),
    sa.Column('pickup_instructions', sa.Text(), nullable=False),
    sa.Column('hauling_cost_per_lb', sa.Float(), nullable=True),
    sa.Column('public_partner_page', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('hauling_cost_per_lb IS NULL OR hauling_cost_per_lb >= 0', name='ck_hauling'),
    sa.CheckConstraint('totes_on_hand >= 0 AND totes_out >= 0', name='ck_totes'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('is_demo_account', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notification_prefs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(role IN ('volunteer', 'admin')) = (organization_id IS NULL)", name='ck_users_org_membership'),
    sa.CheckConstraint("role IN ('restaurant_staff', 'restaurant_manager', 'volunteer', 'org_staff', 'org_manager', 'admin')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)

    op.create_table('intake_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=2), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('answered_by', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("question IN ('Q1', 'Q2', 'Q3')", name='ck_intake_question'),
    sa.ForeignKeyConstraint(['answered_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('intake_answers', schema=None) as batch_op:
        batch_op.create_index('ix_intake_org_q', ['organization_id', 'question', 'answered_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('receiver_profiles',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=True),
    sa.Column('cutoff_minutes', sa.Integer(), nullable=True),
    sa.Column('receiving_contact_name', sa.String(length=120), nullable=False),
    sa.Column('receiving_contact_phone', sa.String(length=40), nullable=False),
    sa.Column('receiving_instructions', sa.Text(), nullable=False),
    sa.Column('curbside_ok', sa.Boolean(), nullable=True),
    sa.Column('curb_location', sa.String(length=200), nullable=False),
    sa.Column('accepts_hot', sa.Boolean(), nullable=True),
    sa.Column('hot_max_minutes', sa.Integer(), nullable=True),
    sa.Column('can_hold_hot', sa.Boolean(), nullable=True),
    sa.Column('serves_immediately', sa.String(length=200), nullable=False),
    sa.Column('accepts_cold', sa.Boolean(), nullable=True),
    sa.Column('fridge_capacity_meals', sa.Integer(), nullable=True),
    sa.Column('accepts_frozen', sa.Boolean(), nullable=True),
    sa.Column('freezer_capacity_meals', sa.Integer(), nullable=True),
    sa.Column('accepts_shelf_stable', sa.Boolean(), nullable=True),
    sa.Column('dietary_rules', sa.JSON(), nullable=False),
    sa.Column('refused_allergens', sa.JSON(), nullable=False),
    sa.Column('max_meals_per_delivery', sa.Integer(), nullable=True),
    sa.Column('typical_nightly_need', sa.Integer(), nullable=True),
    sa.Column('current_need', sa.Integer(), nullable=True),
    sa.Column('current_need_at', sa.DateTime(), nullable=True),
    sa.Column('required_fields', sa.JSON(), nullable=True),
    sa.Column('report_frequency', sa.String(length=20), nullable=True),
    sa.Column('report_format', sa.String(length=10), nullable=True),
    sa.Column('reports_to', sa.String(length=300), nullable=False),
    sa.Column('is_501c3', sa.Boolean(), nullable=True),
    sa.Column('ein', sa.String(length=20), nullable=True),
    sa.Column('ein_verified', sa.Boolean(), nullable=False),
    sa.Column('ein_verified_by', sa.Integer(), nullable=True),
    sa.Column('ein_verified_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(NOT is_501c3 OR is_501c3 IS NULL) OR (ein IS NOT NULL AND ein != '')", name='ck_ein_required'),
    sa.CheckConstraint('cutoff_minutes IS NULL OR cutoff_minutes >= 0', name='ck_cutoff'),
    sa.CheckConstraint('max_meals_per_delivery IS NULL OR max_meals_per_delivery > 0', name='ck_max_meals'),
    sa.ForeignKeyConstraint(['ein_verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('recovery_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_org_id', sa.Integer(), nullable=False),
    sa.Column('receiver_org_id', sa.Integer(), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recovery_agreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recovery_agreements_restaurant_org_id'), ['restaurant_org_id'], unique=False)

    op.create_table('rescue_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescue_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rescue_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('surplus_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.String(length=80), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('surplus_meals', sa.Integer(), nullable=False),
    sa.Column('surplus_lbs', sa.Float(), nullable=False),
    sa.Column('safe_to_donate', sa.Boolean(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('food_categories', sa.String(length=200), nullable=False),
    sa.Column('ready_time', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("disposition IN ('discarded', 'composted', 'donated', 'sold_discounted', 'staff_meal', 'no_surplus')", name='ck_surplus_logs_disposition'),
    sa.CheckConstraint('(prospect_id IS NULL) != (restaurant_id IS NULL)', name='ck_surplus_logs_owner'),
    sa.CheckConstraint('surplus_lbs >= 0', name='ck_surplus_logs_lbs'),
    sa.CheckConstraint('surplus_meals >= 0', name='ck_surplus_logs_meals'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prospect_id', 'log_date', name='uq_surplus_logs_prospect_day'),
    sa.UniqueConstraint('restaurant_id', 'log_date', name='uq_surplus_logs_restaurant_day')
    )
    with op.batch_alter_table('surplus_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surplus_logs_prospect_id'), ['prospect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_surplus_logs_restaurant_id'), ['restaurant_id'], unique=False)

    op.create_table('volunteer_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('availability', sa.JSON(), nullable=False),
    sa.Column('max_distance_mi', sa.Float(), nullable=False),
    sa.Column('capacity_meals', sa.Integer(), nullable=False),
    sa.Column('has_cooler', sa.Boolean(), nullable=False),
    sa.Column('has_insulated_bags', sa.Boolean(), nullable=False),
    sa.Column('preferred_areas', sa.String(length=200), nullable=False),
    sa.Column('vehicle_description', sa.String(length=120), nullable=False),
    sa.Column('home_lat', sa.Float(), nullable=False),
    sa.Column('home_lng', sa.Float(), nullable=False),
    sa.Column('last_lat', sa.Float(), nullable=True),
    sa.Column('last_lng', sa.Float(), nullable=True),
    sa.Column('last_location_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('capacity_meals > 0', name='ck_vol_capacity'),
    sa.CheckConstraint('max_distance_mi > 0', name='ck_vol_distance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('recurring_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('local_time', sa.String(length=5), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_draft_for', sa.Date(), nullable=True),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_sched_weekday'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['rescue_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_schedules_organization_id'), ['organization_id'], unique=False)

    op.create_table('rescues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_org_id', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('meals_per_unit', sa.Float(), nullable=False),
    sa.Column('est_meals', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=14), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('allergens', sa.JSON(), nullable=False),
    sa.Column('allergens_declared', sa.Boolean(), nullable=False),
    sa.Column('dietary_tags', sa.JSON(), nullable=False),
    sa.Column('attested_by', sa.Integer(), nullable=True),
    sa.Column('attested_at', sa.DateTime(), nullable=True),
    sa.Column('safe_until', sa.DateTime(), nullable=False),
    sa.Column('pickup_deadline', sa.DateTime(), nullable=False),
    sa.Column('pickup_instructions', sa.Text(), nullable=False),
    sa.Column('pickup_code', sa.String(length=8), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=False),
    sa.Column('fmv_per_meal', sa.Float(), nullable=True),
    sa.Column('cost_basis_per_meal', sa.Float(), nullable=True),
    sa.Column('allowed_modes', sa.JSON(), nullable=False),
    sa.Column('excluded_volunteer_ids', sa.JSON(), nullable=False),
    sa.Column('requeue_count', sa.Integer(), nullable=False),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("category IN ('hot', 'cold', 'frozen', 'shelf_stable')", name='ck_rescue_category'),
    sa.CheckConstraint("status IN ('posted', 'matched', 'en_route_pickup', 'picked_up', 'en_route_dropoff', 'delivered', 'received', 'cancelled', 'expired', 'rejected', 'reassigned')", name='ck_rescue_status'),
    sa.CheckConstraint("unit IN ('individual_meal', 'bag', 'box', 'tray', 'half_pan', 'full_pan')", name='ck_rescue_unit'),
    sa.CheckConstraint('is_draft OR (attested_by IS NOT NULL AND attested_at IS NOT NULL)', name='ck_rescue_attested'),
    sa.CheckConstraint('quantity > 0 AND est_meals > 0', name='ck_rescue_quantity'),
    sa.ForeignKeyConstraint(['attested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of'], ['rescues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restaurant_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['recurring_schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rescues', schema=None) as batch_op:
        batch_op.create_index('ix_rescue_org_created', ['restaurant_org_id', 'created_at'], unique=False)
        batch_op.create_index('ix_rescue_status_safe_until', ['status', 'safe_until'], unique=False)

    op.create_table('matching_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('estimated_arrival_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matching_explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_explanations_rescue_id'), ['rescue_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('volunteer_user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handoff_state', sa.String(length=20), nullable=True),
    sa.Column('mode_reason', sa.Text(), nullable=False),
    sa.Column('estimated', sa.Boolean(), nullable=False),
    sa.Column('eta_pickup_at', sa.DateTime(), nullable=False),
    sa.Column('load_deadline', sa.DateTime(), nullable=True),
    sa.Column('unload_deadline', sa.DateTime(), nullable=True),
    sa.Column('picked_up_meals', sa.Integer(), nullable=True),
    sa.Column('pickup_photo_url', sa.String(length=500), nullable=False),
    sa.Column('totes_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('route', sa.JSON(), nullable=False),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(mode = 'volunteer') = (volunteer_user_id IS NOT NULL)", name='ck_trip_carrier'),
    sa.CheckConstraint("(mode = 'volunteer') OR simulated", name='ck_trip_av_simulated'),
    sa.CheckConstraint("handoff_state IS NULL OR handoff_state IN ('vehicle_arriving', 'at_pickup_curb', 'loading', 'loaded', 'in_transit', 'at_dropoff_curb', 'unloaded', 'received')", name='ck_trip_handoff'),
    sa.CheckConstraint("mode IN ('volunteer', 'waymo_sim', 'robot_sim')", name='ck_trip_mode'),
    sa.CheckConstraint("status IN ('matched', 'en_route_pickup', 'picked_up', 'en_route_dropoff', 'delivered', 'received', 'cancelled', 'expired', 'rejected', 'reassigned')", name='ck_trip_status'),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index('ix_trip_volunteer_status', ['volunteer_user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_rescue_id'), ['rescue_id'], unique=False)

    op.create_table('trip_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('leg_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('actual_minutes', sa.Float(), nullable=False),
    sa.Column('predicted_p50', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('actual_minutes >= 0', name='ck_trip_legs_minutes'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_legs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_legs_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('allocated_meals', sa.Integer(), nullable=False),
    sa.Column('dropoff_code', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('eta_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('received_meals', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('reject_reason', sa.String(length=12), nullable=True),
    sa.Column('reject_note', sa.String(length=300), nullable=False),
    sa.Column('temperature_f', sa.Float(), nullable=True),
    sa.Column('received_by_name', sa.String(length=120), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('incomplete_fields', sa.JSON(), nullable=False),
    sa.Column('meals_served', sa.Integer(), nullable=True),
    sa.Column('approaching_notified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("condition IS NULL OR condition = 'accepted' OR reject_reason IS NOT NULL", name='ck_stop_reason_required'),
    sa.CheckConstraint("condition IS NULL OR condition IN ('accepted', 'partially_accepted', 'rejected')", name='ck_stop_condition'),
    sa.CheckConstraint("reject_reason IS NULL OR reject_reason IN ('temperature', 'packaging', 'quantity', 'other')", name='ck_stop_reject'),
    sa.CheckConstraint("status IN ('pending', 'delivered', 'received', 'rejected', 'rerouted', 'cancelled')", name='ck_stop_status'),
    sa.CheckConstraint('allocated_meals > 0', name='ck_stop_meals'),
    sa.CheckConstraint('received_meals IS NULL OR received_meals >= 0', name='ck_stop_received'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.create_index('ix_stop_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_stops_trip_id'), ['trip_id'], unique=False)

    op.create_table('acknowledgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('donor_org_id', sa.Integer(), nullable=False),
    sa.Column('receiver_org_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('signer_name', sa.String(length=120), nullable=False),
    sa.Column('signed_by', sa.Integer(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending_signature', 'signed')", name='ck_ack_status'),
    sa.ForeignKeyConstraint(['donor_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stop_id')
    )
    with op.batch_alter_table('acknowledgments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acknowledgments_donor_org_id'), ['donor_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acknowledgments_receiver_org_id'), ['receiver_org_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rescue_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.Column('entity', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rescue_id'], ['rescues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_rescue_at', ['rescue_id', 'at'], unique=False)

    # ### end Alembic commands ###
    for stmt in APPEND_ONLY[op.get_context().dialect.name]:
        op.execute(stmt)


def downgrade() -> None:
    """Downgrade schema."""
    for stmt in DROP_APPEND_ONLY[op.get_context().dialect.name]:
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_rescue_at')

    op.drop_table('audit_events')
    with op.batch_alter_table('acknowledgments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acknowledgments_receiver_org_id'))
        batch_op.drop_index(batch_op.f('ix_acknowledgments_donor_org_id'))

    op.drop_table('acknowledgments')
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_stops_trip_id'))
        batch_op.drop_index('ix_stop_org_status')

    op.drop_table('trip_stops')
    with op.batch_alter_table('trip_legs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_legs_trip_id'))

    op.drop_table('trip_legs')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_rescue_id'))
        batch_op.drop_index('ix_trip_volunteer_status')

    op.drop_table('trips')
    with op.batch_alter_table('matching_explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_explanations_rescue_id'))

    op.drop_table('matching_explanations')
    with op.batch_alter_table('rescues', schema=None) as batch_op:
        batch_op.drop_index('ix_rescue_status_safe_until')
        batch_op.drop_index('ix_rescue_org_created')

    op.drop_table('rescues')
    with op.batch_alter_table('recurring_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_schedules_organization_id'))

    op.drop_table('recurring_schedules')
    op.drop_table('volunteer_profiles')
    with op.batch_alter_table('surplus_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surplus_logs_restaurant_id'))
        batch_op.drop_index(batch_op.f('ix_surplus_logs_prospect_id'))

    op.drop_table('surplus_logs')
    with op.batch_alter_table('rescue_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rescue_templates_organization_id'))

    op.drop_table('rescue_templates')
    with op.batch_alter_table('recovery_agreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recovery_agreements_restaurant_org_id'))

    op.drop_table('recovery_agreements')
    op.drop_table('receiver_profiles')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('intake_answers', schema=None) as batch_op:
        batch_op.drop_index('ix_intake_org_q')

    op.drop_table('intake_answers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('restaurant_profiles')
    with op.batch_alter_table('receiving_exceptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receiving_exceptions_organization_id'))

    op.drop_table('receiving_exceptions')
    with op.batch_alter_table('org_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_reports_organization_id'))

    op.drop_table('org_reports')
    with op.batch_alter_table('impact_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_events_delivery_id'))

    op.drop_table('impact_events')
    op.drop_table('organizations')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_key_at')

    op.drop_table('login_attempts')
    op.drop_table('job_locks')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
